[package]
name = "git_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
eframe = "0.21.3"
egui = "0.21.0"
egui_extras = "0.21.0"
git2 = "0.16.1"
itertools = "0.10.5"
lazy_static = "1.4.0"
tracing-subscriber = "0.3.16"
